#!/usr/bin/env bash
# install-claude-plugins.sh
#
# Build-time installer for Claude Code plugins listed in
# claude-plugins.txt. For each non-comment line, clones the plugin
# repo into /opt/ai-sandbox/plugins/<name>/ and pins to <ref> if
# provided. After all plugins are installed, generates
# /usr/local/bin/claude as a wrapper that exec's the real claude
# binary with --plugin-dir flags for each baked plugin.
#
# Usage: install-claude-plugins.sh <path-to-claude-plugins.txt>
set -euo pipefail

if [ $# -ne 1 ]; then
    echo "usage: $0 <claude-plugins.txt>" >&2
    exit 2
fi

LIST="$1"
PLUGINS_DIR="/opt/ai-sandbox/plugins"
WRAPPER="/usr/local/bin/claude"

# Resolve the real claude binary BEFORE we shadow it with the wrapper.
REAL_CLAUDE="$(command -v claude || true)"
if [ -z "$REAL_CLAUDE" ]; then
    echo "ERROR: 'claude' binary not found on PATH at install time." >&2
    echo "       This script must run AFTER the Claude CLI install layer." >&2
    exit 1
fi
# Resolve symlinks so the wrapper has an absolute, stable path.
REAL_CLAUDE="$(readlink -f "$REAL_CLAUDE")"

mkdir -p "$PLUGINS_DIR"

PLUGIN_NAMES=()
while IFS=' ' read -r name url ref || [ -n "${name:-}" ]; do
    # Skip blank lines and comments.
    case "$name" in
        ''|'#'*) continue ;;
    esac
    if [ -z "${url:-}" ]; then
        echo "ERROR: malformed line in $LIST: '$name' (missing url column)" >&2
        exit 1
    fi
    dest="$PLUGINS_DIR/$name"
    echo "==> Installing $name from $url${ref:+ @ $ref}"
    rm -rf "$dest"
    git clone --depth 1 "$url" "$dest"
    if [ -n "${ref:-}" ]; then
        git -C "$dest" fetch --depth 1 origin "$ref"
        git -C "$dest" checkout "$ref"
    fi
    git -C "$dest" rev-parse HEAD > "$dest/.installed-sha"
    # Sanity-check: a Claude plugin has either a manifest at
    # .claude-plugin/plugin.json or one of the standard component
    # directories. Reject repos that have neither.
    if [ ! -f "$dest/.claude-plugin/plugin.json" ] \
       && [ ! -d "$dest/skills" ] \
       && [ ! -d "$dest/commands" ] \
       && [ ! -d "$dest/agents" ] \
       && [ ! -d "$dest/hooks" ]; then
        echo "ERROR: $name (cloned from $url) does not look like a Claude plugin." >&2
        echo "       Expected .claude-plugin/plugin.json or skills/commands/agents/hooks dir." >&2
        exit 1
    fi
    PLUGIN_NAMES+=("$name")
done < "$LIST"

# Generate /usr/local/bin/claude wrapper. Use printf to avoid
# escaping subtleties with heredocs and embedded $ signs.
{
    printf '%s\n' '#!/bin/sh'
    printf '%s\n' '# Generated by install-claude-plugins.sh. Do not edit; rebuild the image.'
    printf 'exec %s' "$REAL_CLAUDE"
    for name in "${PLUGIN_NAMES[@]+"${PLUGIN_NAMES[@]}"}"; do
        printf ' \\\n    --plugin-dir %s/%s' "$PLUGINS_DIR" "$name"
    done
    printf ' \\\n    "$@"\n'
} > "$WRAPPER"
chmod +x "$WRAPPER"

echo "==> Installed ${#PLUGIN_NAMES[@]} plugin(s); generated wrapper:"
sed 's/^/    /' "$WRAPPER"
